### ISSUE TITLE
Название и логика немного не те 

### ISSUE THREAD

**Issue by NickSettler** [VKaysarov/Photo-Service-WorldSkills-#1]
https://github.com/VKaysarov/module3/blob/bb48ae79ade1ced982e711358807ca35ead869e3/Module3/index.php#L9
expansion это типо расширение файла имеется ввиду? тут скорее подойдет extension. expansion тоже переводится как расширение, но это имеется ввиду какое то физическое расширение. типо расширение объема или че нибудь такое
и кстати второй элемент массива в таком случае не факт, что является расширением файла
если файл будет называться script.min.js то по такой логике расширение будет min

**Comment by VKaysarov** [comment]
Я просто не сообразил как последний элемент массива вытаскивать, в Python это explode_img[-1].
Но тут это не сработало, и $explode_img[count($explode_img)] тоже не сработало
